### ISSUE TITLE
Error install npm

### ISSUE THREAD

**Issue by oenrico** [MetlHedd/todolist#3]
Hi i install but error npn

13267 error Linux 4.15.0-29-generic
13268 error argv "/usr/bin/node" "/usr/bin/npm" "install"
13269 error node v8.10.0
13270 error npm  v3.5.2
13271 error code EMISSINGARG
13272 error typeerror Error: Missing required argument #1
13272 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
13272 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
13272 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
13272 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
13272 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
13272 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
13272 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
13272 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
13272 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
13272 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
13273 error typeerror This is an error with npm itself. Please report this error at:
13273 error typeerror     <http://github.com/npm/npm/issues>
13274 verbose exit [ 1, true ]

Thank you very mutch

**Comment by MetlHedd** [comment]
As the command say `13273 error typeerror This is an error with npm itself. Please report this error at:`, it's a npm error, so u prob need to update your npm version.
